language: d

install:
  # fdb
  - FDB_VER=3.0.4
  - FDB=foundationdb-clients_${FDB_VER}-1_amd64.deb
  - sudo apt-get -y update || true
  - sudo apt-get -fy install || true
  # get fdb
  - wget https://foundationdb.com/downloads/I_accept_the_FoundationDB_Community_License_Agreement/key-value-store/${FDB_VER}/${FDB}
  - sudo dpkg -i ${FDB} || true

script:
  - dub test
  - for ex in `\ls -1 examples/`; do (echo "[INFO] Building example $ex"; cd examples/$ex && dub build) || exit 1; done
  # - for ex in `\ls -1 tests/`; do (echo "[INFO] Running test $ex"; cd tests/$ex && dub) || exit 1; done
